run_mode: compound

router:
  type: transformer
  model_path: "model-store/router_model"
  max_length: 512
  confidence_threshold: 0.8
  device: null

small_llm:
  type: "ollama"
  model_name: "llama3.2:3b"
  host: "http://localhost:11434"

large_llm:
  type: "openai"
  model_name: "gpt-4o-mini"
  api_key: ${oc.env:OPENAI_API_KEY}
  max_tokens: 1000

evaluation:
  output_dir: "results/openai_comparison"
  num_samples: 500
  seed: 42
  output_file: "results/openai_comparison/openai_comparison_results.json"