# @package _global_
defaults:
  - default

# Compound AI System: Transformer Router with GPT-4o-mini and Phi-2

experiment_name: "transformer_router_gpt4o_mini_phi2"
run_mode: "compound"

# Router configuration
router:
  model_path: "model-store/router_model"
  confidence_threshold: 0.7
  max_length: 512
  device: null

# Model configuration
small_llm:
  type: "ollama"
  model_name: "phi:latest"
  host: "http://localhost:11434"
    
large_llm:
  type: "openai"
  model_name: "gpt-4o-mini"
  api_key: ${oc.env:OPENAI_API_KEY}

# Evaluation configuration
evaluation:
  output_dir: "results/experiments/compound/transformer_router/gpt_phi"
  num_samples: 500
  seed: 42
  output_file: "results/experiments/compound/transformer_router/gpt_phi/evaluation_results.json"