# @package _global_
defaults:
  - default

# Compound AI System Evaluation Configuration
# Transformer Router (DistilBERT) with Claude Haiku and Llama3.2 3B

experiment_name: "transformer_router_claude_haiku_llama3b"
run_mode: "compound"

# Router configuration
router:
  model_path: "model-store/router_model"  # Path to trained DistilBERT router
  confidence_threshold: 0.7  # Threshold for routing decisions
  max_length: 512
  device: null

# Model configuration
small_llm:
  type: "ollama"
  model_name: "llama3.2:3b"
  host: "http://localhost:11434"
    
large_llm:
  type: "claude"
  model_name: "claude-3-haiku-20240307"
  api_key: ${oc.env:ANTHROPIC_API_KEY}

# Evaluation configuration
evaluation:
  output_dir: "results/experiments/compound/transformer_router/claude_3b"
  num_samples: 3500  # Full ARC evaluation set
  seed: 42
  output_file: "results/experiments/compound/transformer_router/claude_3b/evaluation_results.json"