router:
  model_path: "model-store/router_model"
  max_length: 512
  confidence_threshold: 0.8
  device: null

small_llm:
  type: "ollama"
  model_name: "llama3"
  host: "http://localhost:11434"

large_llm:
  type: "claude"
  model_name: "claude-3-haiku-20240307"
  api_key: ${oc.env:ANTHROPIC_API_KEY}

evaluation:
  output_dir: "results/test_run"
  num_samples: 500
  seed: 42
  output_file: "results/test_run/evaluation_results.json"